name: Build All

on: [push]

jobs:

  build_scala2_13:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Cache Coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: ${{ runner.os }}-coursier-scala-2_13-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-coursier-scala-2_13-

      - name: Cache Ivy
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-ivy-scala-2_13-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-ivy-scala-2_13-

      - name: Build for Scala 2.13
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: .github/workflows/sbt-build.sh 2.13.1

#      - name: Build cli
#        run: |
#          sbt -J-Xmx2048m "; project cli; ++2.13.1!; clean; universal:packageBin; universal:packageZipTarball; debian:packageBin"
#          ls -ld cli/target/jdk-symbolic-link-cli*
#          ls -ld cli/target/universal/jdk-symbolic-link-cli*
